# Generated by Django 3.1.3 on 2021-03-23 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MSCEapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='setting',
            name='logo',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
    ]
