# Generated by Django 3.1.3 on 2021-03-24 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MSCEapp', '0003_contactmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='setting',
            name='slider_image',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
    ]
