# Generated by Django 3.1.3 on 2021-03-24 08:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ConstructApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200)),
                ('image', models.ImageField(blank=True, upload_to='product/')),
                ('constructionproject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ConstructApp.constructionproject')),
            ],
        ),
    ]
