# Generated by Django 3.1.3 on 2021-03-24 18:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ConstructApp', '0002_images'),
        ('serviceMSCE', '0002_services_titleicon'),
    ]

    operations = [
        migrations.CreateModel(
            name='MSCETeam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='team/')),
                ('details', models.TextField()),
                ('facebook_url', models.CharField(blank=True, max_length=200, null=True)),
                ('twitter_url', models.CharField(blank=True, max_length=200, null=True)),
                ('instagram_url', models.CharField(blank=True, max_length=200, null=True)),
                ('youtube_url', models.CharField(blank=True, max_length=200, null=True)),
                ('status', models.CharField(choices=[('True', 'True'), ('False', 'False')], max_length=30)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('sp_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ConstructApp.constructioncategory')),
            ],
        ),
    ]
