# Generated by Django 3.1.3 on 2021-03-24 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serviceMSCE', '0003_msceteam'),
    ]

    operations = [
        migrations.AlterField(
            model_name='msceteam',
            name='facebook_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='msceteam',
            name='instagram_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='msceteam',
            name='twitter_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='msceteam',
            name='youtube_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
